# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c951d3fba77558c0382aa65a53148bf48cfdc19bb4e8e797fec4e66bd0aad22a8f066d454040b86b3e9303fca4ad718dc5aa7a61a282f6725a7f8530a91ea97

test:
  secret_key_base: c4e8479af59941ab90f7143a419aa51bf31652c759c629cb208befcfb18210b39366c756a1de8bf84b71bf2d79f34275ef1c6eb4a853882cb6d13e0e7023bd07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
